using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

namespace ASB.ExcelImport.Editor
{
    public static class CodeGenerator
    {
        private const string AutoGeneratedHeader = "// ⚠️ Auto Generated. Do not modify.";

        private static readonly HashSet<string> ReservedTypeNames = new HashSet<string>(StringComparer.Ordinal)
        {
            "ExcelSheetParseResult",
            "ExcelParsedSheet",
            "ParsedSheet",
            "ExcelParser",
            "ExcelImportPaths",
            "ExcelEditorWindow",
            "ScriptableExporter"
        };

        public static void GenerateAll(IReadOnlyList<ExcelSheetParseResult> sheets)
        {
            if (sheets == null || sheets.Count == 0)
            {
                Debug.LogWarning("[CodeGenerator] No sheets to generate.");
                return;
            }

            string outputFolder = ExcelImportPaths.GeneratedScriptFolder;
            Directory.CreateDirectory(ToAbsoluteAssetPath(outputFolder));

            for (int i = 0; i < sheets.Count; i++)
            {
                ExcelSheetParseResult sheet = sheets[i];
                if (sheet == null)
                {
                    continue;
                }

                GenerateSheetScripts(sheet, outputFolder);
            }
        }

        private static void GenerateSheetScripts(ExcelSheetParseResult sheet, string outputFolder)
        {
            string baseName = ToTypeBaseName(sheet.SheetName);
            string rowClassName = baseName + "Data";
            string tableClassName = baseName + "DataTable";

            if (IsReservedTypeName(rowClassName) || IsReservedTypeName(tableClassName))
            {
                Debug.LogError(
                    $"[CodeGenerator] Skip sheet '{sheet.SheetName}': generated type name '{rowClassName}' conflicts with editor parser types. Rename the excel sheet tab.");
                return;
            }

            string rowFilePath = $"{outputFolder}/{rowClassName}.cs";
            string tableFilePath = $"{outputFolder}/{tableClassName}.cs";

            File.WriteAllText(ToAbsoluteAssetPath(rowFilePath), BuildRowClass(rowClassName, sheet), Encoding.UTF8);
            File.WriteAllText(ToAbsoluteAssetPath(tableFilePath), BuildTableClass(tableClassName, rowClassName, baseName), Encoding.UTF8);

            Debug.Log($"[CodeGenerator] Generated: {rowFilePath}, {tableFilePath}");
        }

        private static bool IsReservedTypeName(string typeName)
        {
            return !string.IsNullOrEmpty(typeName) && ReservedTypeNames.Contains(typeName);
        }

        private static string BuildRowClass(string className, ExcelSheetParseResult sheet)
        {
            var sb = new StringBuilder();
            sb.AppendLine(AutoGeneratedHeader);
            sb.AppendLine();
            sb.AppendLine("[System.Serializable]");
            sb.AppendLine($"public class {className}");
            sb.AppendLine("{");

            for (int i = 0; i < sheet.Names.Count; i++)
            {
                string fieldName = SanitizeFieldName(sheet.Names[i]);
                string csharpType = ToCSharpType(sheet.Types[i]);
                sb.AppendLine($"    public {csharpType} {fieldName};");
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string BuildTableClass(string tableClassName, string rowClassName, string menuBaseName)
        {
            var sb = new StringBuilder();
            sb.AppendLine(AutoGeneratedHeader);
            sb.AppendLine();
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine($"[CreateAssetMenu(fileName=\"{tableClassName}\", menuName=\"DataTable/{menuBaseName}\")]");
            sb.AppendLine($"public class {tableClassName} : ScriptableObject");
            sb.AppendLine("{");
            sb.AppendLine($"    public List<{rowClassName}> DataList = new List<{rowClassName}>();");
            sb.AppendLine("}");
            return sb.ToString();
        }

        public static string ToTypeBaseName(string sheetName)
        {
            if (string.IsNullOrWhiteSpace(sheetName))
            {
                return "Sheet";
            }

            var sb = new StringBuilder();
            bool nextUpper = true;
            for (int i = 0; i < sheetName.Length; i++)
            {
                char c = sheetName[i];
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(nextUpper ? char.ToUpperInvariant(c) : c);
                    nextUpper = false;
                }
                else
                {
                    nextUpper = true;
                }
            }

            string result = sb.ToString();
            if (string.IsNullOrEmpty(result))
            {
                result = "Sheet";
            }

            if (char.IsDigit(result[0]))
            {
                result = "_" + result;
            }

            return result;
        }

        public static string SanitizeFieldName(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                return "field";
            }

            var sb = new StringBuilder();
            for (int i = 0; i < name.Length; i++)
            {
                char c = name[i];
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    sb.Append(c);
                }
                else
                {
                    sb.Append('_');
                }
            }

            string result = sb.ToString();
            if (string.IsNullOrEmpty(result))
            {
                return "field";
            }

            if (char.IsDigit(result[0]))
            {
                result = "_" + result;
            }

            return result;
        }

        private static string ToCSharpType(string excelType)
        {
            switch (excelType?.Trim().ToLowerInvariant())
            {
                case "int":
                    return "int";
                case "float":
                    return "float";
                case "bool":
                    return "bool";
                case "string":
                    return "string";
                default:
                    Debug.LogWarning($"[CodeGenerator] Unknown type '{excelType}', fallback to string.");
                    return "string";
            }
        }

        private static string ToAbsoluteAssetPath(string unityAssetPath)
        {
            string relative = unityAssetPath.Replace('\\', '/');
            if (relative.StartsWith("Assets/", StringComparison.OrdinalIgnoreCase))
            {
                relative = relative.Substring("Assets/".Length);
            }

            return Path.Combine(Application.dataPath, relative);
        }
    }
}
