using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using UnityEngine;

namespace ASB.ExcelImport.Editor
{
    public static class CodeGenerator
    {
        private const string AutoGeneratedHeader = "// Auto Generated. Do not modify.";

        private static readonly HashSet<string> ReservedTypeNames = new HashSet<string>(StringComparer.Ordinal)
        {
            "ExcelSheetParseResult",
            "ExcelParsedSheet",
            "ParsedSheet",
            "ExcelParser",
            "ExcelImportPaths",
            "ExcelEditorWindow",
            "ScriptableExporter"
        };

        // ─────────────────────────────────────────────
        // Public API
        // ─────────────────────────────────────────────

        public static void GenerateAll(IReadOnlyList<ExcelSheetParseResult> sheets, Dictionary<string, bool> useDictMap = null)
        {
            if (sheets == null || sheets.Count == 0)
            {
                Debug.LogWarning("[CodeGenerator] No sheets to generate.");
                return;
            }

            string outputFolder = ExcelImportPaths.GeneratedScriptFolder;
            Directory.CreateDirectory(ToAbsoluteAssetPath(outputFolder));

            for (int i = 0; i < sheets.Count; i++)
            {
                ExcelSheetParseResult sheet = sheets[i];
                if (sheet == null) continue;

                bool useDict = useDictMap != null && useDictMap.TryGetValue(sheet.SheetName, out bool val) && val;
                GenerateSheetScript(sheet, outputFolder, useDict);
            }
        }

        // ─────────────────────────────────────────────
        // 시트 → 파일 1개 생성
        // ─────────────────────────────────────────────

        private static void GenerateSheetScript(ExcelSheetParseResult sheet, string outputFolder, bool useDictionary)
        {
            string baseName       = ToTypeBaseName(sheet.ClassName);
            string rowClassName   = baseName + "Data";
            string tableClassName = baseName + "DataTable";

            if (IsReservedTypeName(rowClassName) || IsReservedTypeName(tableClassName))
            {
                Debug.LogError(
                    $"[CodeGenerator] Skip sheet '{sheet.SheetName}': type name '{rowClassName}' conflicts with editor types. Rename the sheet tab.");
                return;
            }

            string filePath = $"{outputFolder}/{tableClassName}.cs";
            string code     = BuildSheetScript(sheet, rowClassName, tableClassName, baseName, useDictionary);
            string absolutePath = ToAbsoluteAssetPath(filePath);

            // 생성 타입은 전역 네임스페이스라 손으로 쓴 동명 타입과 CS0101(중복 정의)로 충돌한다.
            // 예: 시트 탭을 "Skill"로 두면 Model/SkillData.cs와 부딪혀 프로젝트 전체가 컴파일 에러로 잠기고,
            // 에디터 창도 못 열어 손으로 .cs를 지워야 복구된다. 디스크에 쓰기 전에 끊는다.
            // 이미 생성 폴더에 파일이 있으면 그 타입은 우리가 만든 것이므로 검사하지 않는다.
            if (!File.Exists(absolutePath) &&
                (TryFindConflictingGlobalType(rowClassName, out string conflictOwner) ||
                 TryFindConflictingGlobalType(tableClassName, out conflictOwner)))
            {
                Debug.LogError(
                    $"[CodeGenerator] Skip sheet '{sheet.SheetName}': 전역 타입 '{conflictOwner}'이 이미 존재해 " +
                    "생성 타입과 중복 정의(CS0101)가 된다. 시트 탭 이름을 바꿀 것.");
                return;
            }

            if (File.Exists(absolutePath))
            {
                string existing = File.ReadAllText(absolutePath, Encoding.UTF8);
                if (existing == code)
                {
                    Debug.Log($"[CodeGenerator] Unchanged: {filePath}");
                    return;
                }

                string existingSignature = ExtractTemplateSignature(existing);
                if (string.IsNullOrEmpty(sheet.TemplateSignature) &&
                    !string.IsNullOrEmpty(existingSignature))
                {
                    Debug.LogWarning(
                        $"[CodeGenerator] Existing script has Template Signature, but new generation has none. " +
                        $"Marker-based generation may overwrite a Raw/Schema shared template script: {filePath}");
                }

                if (!string.IsNullOrEmpty(sheet.TemplateSignature) &&
                    !string.IsNullOrEmpty(existingSignature) &&
                    !string.Equals(existingSignature, sheet.TemplateSignature, StringComparison.Ordinal))
                {
                    throw new InvalidOperationException(
                        $"[CodeGenerator] Refusing to overwrite shared template script '{filePath}'. " +
                        $"Existing signature '{existingSignature}' differs from new signature '{sheet.TemplateSignature}'.");
                }
            }

            File.WriteAllText(absolutePath, code, Encoding.UTF8);
            Debug.Log($"[CodeGenerator] Generated: {filePath}");
        }

        // ─────────────────────────────────────────────
        // 단일 빌더 — 데이터 클래스 + 컨테이너 클래스를 한 파일에 작성
        // ─────────────────────────────────────────────

        private static string BuildSheetScript(
            ExcelSheetParseResult sheet,
            string rowClassName,
            string tableClassName,
            string menuBaseName,
            bool useDictionary)
        {
            bool needsList = sheet.Types.Exists(
                t => t != null && t.Trim().StartsWith("list<", StringComparison.OrdinalIgnoreCase));

            string keyFieldName = sheet.Names.Count > 0 ? SanitizeFieldName(sheet.Names[0]) : "id";
            string keyTypeName  = sheet.Types.Count > 0 ? ToCSharpType(sheet.Types[0]) : "int";

            var sb = new StringBuilder();

            // ── using ──────────────────────────────────
            sb.AppendLine(AutoGeneratedHeader);
            if (!string.IsNullOrEmpty(sheet.TemplateSignature))
            {
                sb.AppendLine("// Template Signature: " + sheet.TemplateSignature);
            }
            sb.AppendLine();
            if (useDictionary)
            {
                sb.AppendLine("using System;");
            }
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();

            // ── 데이터 클래스 ───────────────────────────
            sb.AppendLine("[System.Serializable]");
            sb.AppendLine($"public class {rowClassName}");
            sb.AppendLine("{");
            for (int i = 0; i < sheet.Names.Count; i++)
            {
                string fieldName  = SanitizeFieldName(sheet.Names[i]);
                string csharpType = ToCSharpType(sheet.Types[i]);
                sb.AppendLine($"    public {csharpType} {fieldName};");
            }
            sb.AppendLine("}");
            sb.AppendLine();

            // ── 컨테이너 클래스 (List) ───────────────────
            sb.AppendLine($"[CreateAssetMenu(fileName=\"{tableClassName}\", menuName=\"DataTable/{menuBaseName}\")]");

            if (useDictionary)
            {
                // Dictionary 모드 — ISerializationCallbackReceiver
                sb.AppendLine($"public class {tableClassName} : ScriptableObject, ISerializationCallbackReceiver");
                sb.AppendLine("{");
                sb.AppendLine($"    public List<{rowClassName}> DataList = new List<{rowClassName}>();");
                sb.AppendLine();
                sb.AppendLine("    [NonSerialized]");
                sb.AppendLine($"    public Dictionary<{keyTypeName}, {rowClassName}> DataMap = new Dictionary<{keyTypeName}, {rowClassName}>();");
                sb.AppendLine();
                sb.AppendLine("    public void OnBeforeSerialize() { }");
                sb.AppendLine();
                sb.AppendLine("    public void OnAfterDeserialize()");
                sb.AppendLine("    {");
                sb.AppendLine("        DataMap.Clear();");
                sb.AppendLine($"        foreach (var data in DataList)");
                sb.AppendLine("        {");
                sb.AppendLine($"            if (!DataMap.ContainsKey(data.{keyFieldName}))");
                sb.AppendLine("            {");
                sb.AppendLine($"                DataMap.Add(data.{keyFieldName}, data);");
                sb.AppendLine("            }");
                sb.AppendLine("            else");
                sb.AppendLine("            {");
                sb.AppendLine($"                UnityEngine.Debug.LogWarning($\"[{tableClassName}] Duplicate key: {{data.{keyFieldName}}}\");");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");
            }
            else
            {
                // List 모드
                sb.AppendLine($"public class {tableClassName} : ScriptableObject");
                sb.AppendLine("{");
                sb.AppendLine($"    public List<{rowClassName}> DataList = new List<{rowClassName}>();");
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        // ─────────────────────────────────────────────
        // 유틸리티
        // ─────────────────────────────────────────────

        private static bool IsReservedTypeName(string typeName)
        {
            return !string.IsNullOrEmpty(typeName) && ReservedTypeNames.Contains(typeName);
        }

        public static string ExtractTemplateSignature(string code)
        {
            if (string.IsNullOrEmpty(code))
            {
                return string.Empty;
            }

            const string prefix = "// Template Signature:";
            using (var reader = new StringReader(code))
            {
                string line;
                while ((line = reader.ReadLine()) != null)
                {
                    if (line.StartsWith(prefix, StringComparison.Ordinal))
                    {
                        return line.Substring(prefix.Length).Trim();
                    }

                    if (!line.StartsWith("//", StringComparison.Ordinal) && !string.IsNullOrWhiteSpace(line))
                    {
                        return string.Empty;
                    }
                }
            }

            return string.Empty;
        }

        public static string ToTypeBaseName(string sheetName)
        {
            if (string.IsNullOrWhiteSpace(sheetName)) return "Sheet";

            var sb = new StringBuilder();
            bool nextUpper = true;
            for (int i = 0; i < sheetName.Length; i++)
            {
                char c = sheetName[i];
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(nextUpper ? char.ToUpperInvariant(c) : c);
                    nextUpper = false;
                }
                else
                {
                    nextUpper = true;
                }
            }

            string result = sb.ToString();
            if (string.IsNullOrEmpty(result)) result = "Sheet";
            if (char.IsDigit(result[0]))      result = "_" + result;
            return result;
        }

        public static string SanitizeFieldName(string name)
        {
            if (string.IsNullOrWhiteSpace(name)) return "field";

            var sb = new StringBuilder();
            for (int i = 0; i < name.Length; i++)
            {
                char c = name[i];
                sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
            }

            string result = sb.ToString();
            if (string.IsNullOrEmpty(result))  return "field";
            if (char.IsDigit(result[0]))       result = "_" + result;

            // C# 예약어는 그대로 쓰면 컴파일이 깨진다("event" 컬럼 → public string event; → CS1041).
            // 컴파일 에러가 나면 에디터 창도 열 수 없어 손으로 .cs를 지워야 복구되므로 여기서 반드시 걸러야 한다.
            //
            // 축자 식별자(@event)가 아니라 '_' 접두를 쓴다. ScriptableExporter가 이 함수의 반환값을
            // 그대로 rowType.GetField()에 넘기는데, 리플렉션이 보는 필드명에는 @가 없어서
            // @를 붙이면 조회가 null이 되고 그 컬럼 값이 조용히 유실된다.
            if (CSharpKeywords.Contains(result)) result = "_" + result;

            return result;
        }

        /// <summary>
        /// 전역 네임스페이스에 <paramref name="typeName"/>과 같은 이름의 타입이 이미 있는지 찾는다.
        /// 생성 타입은 네임스페이스가 없으므로 <c>FullName == typeName</c>인 타입만 충돌 대상이다.
        /// </summary>
        private static bool TryFindConflictingGlobalType(string typeName, out string owner)
        {
            owner = null;
            if (string.IsNullOrEmpty(typeName))
            {
                return false;
            }

            Assembly[] assemblies = AppDomain.CurrentDomain.GetAssemblies();
            for (int i = 0; i < assemblies.Length; i++)
            {
                Type[] types;
                try
                {
                    types = assemblies[i].GetTypes();
                }
                catch (ReflectionTypeLoadException ex)
                {
                    types = ex.Types;
                }
                catch (Exception)
                {
                    continue;
                }

                if (types == null)
                {
                    continue;
                }

                for (int t = 0; t < types.Length; t++)
                {
                    Type type = types[t];
                    if (type != null && string.Equals(type.FullName, typeName, StringComparison.Ordinal))
                    {
                        owner = $"{typeName} ({assemblies[i].GetName().Name})";
                        return true;
                    }
                }
            }

            return false;
        }

        /// <summary>
        /// C# 예약 키워드 전체. 축자 식별자(@)로 escape 할 대상.
        /// 문맥 키워드(var, value, async 등)는 식별자로 써도 합법이라 제외한다.
        /// </summary>
        private static readonly HashSet<string> CSharpKeywords = new HashSet<string>(StringComparer.Ordinal)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
            "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this",
            "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort",
            "using", "virtual", "void", "volatile", "while"
        };

        public static string ToCSharpType(string excelType)
        {
            switch (excelType?.Trim().ToLowerInvariant())
            {
                case "int":          return "int";
                case "float":        return "float";
                case "bool":         return "bool";
                case "string":       return "string";
                case "percent":      return "float";
                case "list<int>":    return "List<int>";
                case "list<float>":  return "List<float>";
                case "list<string>": return "List<string>";
                case "list<bool>":   return "List<bool>";
                default:
                    Debug.LogWarning($"[CodeGenerator] Unknown type '{excelType}', fallback to string.");
                    return "string";
            }
        }

        private static string ToAbsoluteAssetPath(string unityAssetPath)
        {
            string relative = unityAssetPath.Replace('\\', '/');
            if (relative.StartsWith("Assets/", StringComparison.OrdinalIgnoreCase))
                relative = relative.Substring("Assets/".Length);
            return Path.Combine(Application.dataPath, relative);
        }
    }
}
