using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEngine;

namespace ASB.ExcelImport.Editor
{
    public static class CodeGenerator
    {
        private const string AutoGeneratedHeader = "// Auto Generated. Do not modify.";

        private static readonly HashSet<string> ReservedTypeNames = new HashSet<string>(StringComparer.Ordinal)
        {
            "ExcelSheetParseResult",
            "ExcelParsedSheet",
            "ParsedSheet",
            "ExcelParser",
            "ExcelImportPaths",
            "ExcelEditorWindow",
            "ScriptableExporter"
        };

        // ─────────────────────────────────────────────
        // Public API
        // ─────────────────────────────────────────────

        public static void GenerateAll(IReadOnlyList<ExcelSheetParseResult> sheets, Dictionary<string, bool> useDictMap = null)
        {
            if (sheets == null || sheets.Count == 0)
            {
                Debug.LogWarning("[CodeGenerator] No sheets to generate.");
                return;
            }

            string outputFolder = ExcelImportPaths.GeneratedScriptFolder;
            Directory.CreateDirectory(ToAbsoluteAssetPath(outputFolder));

            for (int i = 0; i < sheets.Count; i++)
            {
                ExcelSheetParseResult sheet = sheets[i];
                if (sheet == null) continue;

                bool useDict = useDictMap != null && useDictMap.TryGetValue(sheet.SheetName, out bool val) && val;
                GenerateSheetScript(sheet, outputFolder, useDict);
            }
        }

        // ─────────────────────────────────────────────
        // 시트 → 파일 1개 생성
        // ─────────────────────────────────────────────

        private static void GenerateSheetScript(ExcelSheetParseResult sheet, string outputFolder, bool useDictionary)
        {
            string baseName       = ToTypeBaseName(sheet.SheetName);
            string rowClassName   = baseName + "Data";
            string tableClassName = baseName + "DataTable";

            if (IsReservedTypeName(rowClassName) || IsReservedTypeName(tableClassName))
            {
                Debug.LogError(
                    $"[CodeGenerator] Skip sheet '{sheet.SheetName}': type name '{rowClassName}' conflicts with editor types. Rename the sheet tab.");
                return;
            }

            string filePath = $"{outputFolder}/{tableClassName}.cs";
            string code     = BuildSheetScript(sheet, rowClassName, tableClassName, baseName, useDictionary);

            File.WriteAllText(ToAbsoluteAssetPath(filePath), code, Encoding.UTF8);
            Debug.Log($"[CodeGenerator] Generated: {filePath}");
        }

        // ─────────────────────────────────────────────
        // 단일 빌더 — 데이터 클래스 + 컨테이너 클래스를 한 파일에 작성
        // ─────────────────────────────────────────────

        private static string BuildSheetScript(
            ExcelSheetParseResult sheet,
            string rowClassName,
            string tableClassName,
            string menuBaseName,
            bool useDictionary)
        {
            bool needsList = sheet.Types.Exists(
                t => t != null && t.Trim().StartsWith("list<", StringComparison.OrdinalIgnoreCase));

            string keyFieldName = sheet.Names.Count > 0 ? SanitizeFieldName(sheet.Names[0]) : "id";
            string keyTypeName  = sheet.Types.Count > 0 ? ToCSharpType(sheet.Types[0]) : "int";

            var sb = new StringBuilder();

            // ── using ──────────────────────────────────
            sb.AppendLine(AutoGeneratedHeader);
            sb.AppendLine();
            if (useDictionary)
            {
                sb.AppendLine("using System;");
            }
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();

            // ── 데이터 클래스 ───────────────────────────
            sb.AppendLine("[System.Serializable]");
            sb.AppendLine($"public class {rowClassName}");
            sb.AppendLine("{");
            for (int i = 0; i < sheet.Names.Count; i++)
            {
                string fieldName  = SanitizeFieldName(sheet.Names[i]);
                string csharpType = ToCSharpType(sheet.Types[i]);
                sb.AppendLine($"    public {csharpType} {fieldName};");
            }
            sb.AppendLine("}");
            sb.AppendLine();

            // ── 컨테이너 클래스 (List) ───────────────────
            sb.AppendLine($"[CreateAssetMenu(fileName=\"{tableClassName}\", menuName=\"DataTable/{menuBaseName}\")]");

            if (useDictionary)
            {
                // Dictionary 모드 — ISerializationCallbackReceiver
                sb.AppendLine($"public class {tableClassName} : ScriptableObject, ISerializationCallbackReceiver");
                sb.AppendLine("{");
                sb.AppendLine($"    public List<{rowClassName}> DataList = new List<{rowClassName}>();");
                sb.AppendLine();
                sb.AppendLine("    [NonSerialized]");
                sb.AppendLine($"    public Dictionary<{keyTypeName}, {rowClassName}> DataMap = new Dictionary<{keyTypeName}, {rowClassName}>();");
                sb.AppendLine();
                sb.AppendLine("    public void OnBeforeSerialize() { }");
                sb.AppendLine();
                sb.AppendLine("    public void OnAfterDeserialize()");
                sb.AppendLine("    {");
                sb.AppendLine("        DataMap.Clear();");
                sb.AppendLine($"        foreach (var data in DataList)");
                sb.AppendLine("        {");
                sb.AppendLine($"            if (!DataMap.ContainsKey(data.{keyFieldName}))");
                sb.AppendLine("            {");
                sb.AppendLine($"                DataMap.Add(data.{keyFieldName}, data);");
                sb.AppendLine("            }");
                sb.AppendLine("            else");
                sb.AppendLine("            {");
                sb.AppendLine($"                UnityEngine.Debug.LogWarning($\"[{tableClassName}] Duplicate key: {{data.{keyFieldName}}}\");");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine("}");
            }
            else
            {
                // List 모드
                sb.AppendLine($"public class {tableClassName} : ScriptableObject");
                sb.AppendLine("{");
                sb.AppendLine($"    public List<{rowClassName}> DataList = new List<{rowClassName}>();");
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        // ─────────────────────────────────────────────
        // 유틸리티
        // ─────────────────────────────────────────────

        private static bool IsReservedTypeName(string typeName)
        {
            return !string.IsNullOrEmpty(typeName) && ReservedTypeNames.Contains(typeName);
        }

        public static string ToTypeBaseName(string sheetName)
        {
            if (string.IsNullOrWhiteSpace(sheetName)) return "Sheet";

            var sb = new StringBuilder();
            bool nextUpper = true;
            for (int i = 0; i < sheetName.Length; i++)
            {
                char c = sheetName[i];
                if (char.IsLetterOrDigit(c))
                {
                    sb.Append(nextUpper ? char.ToUpperInvariant(c) : c);
                    nextUpper = false;
                }
                else
                {
                    nextUpper = true;
                }
            }

            string result = sb.ToString();
            if (string.IsNullOrEmpty(result)) result = "Sheet";
            if (char.IsDigit(result[0]))      result = "_" + result;
            return result;
        }

        public static string SanitizeFieldName(string name)
        {
            if (string.IsNullOrWhiteSpace(name)) return "field";

            var sb = new StringBuilder();
            for (int i = 0; i < name.Length; i++)
            {
                char c = name[i];
                sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
            }

            string result = sb.ToString();
            if (string.IsNullOrEmpty(result))  return "field";
            if (char.IsDigit(result[0]))       result = "_" + result;
            return result;
        }

        public static string ToCSharpType(string excelType)
        {
            switch (excelType?.Trim().ToLowerInvariant())
            {
                case "int":          return "int";
                case "float":        return "float";
                case "bool":         return "bool";
                case "string":       return "string";
                case "percent":      return "float";
                case "list<int>":    return "List<int>";
                case "list<float>":  return "List<float>";
                case "list<string>": return "List<string>";
                case "list<bool>":   return "List<bool>";
                default:
                    Debug.LogWarning($"[CodeGenerator] Unknown type '{excelType}', fallback to string.");
                    return "string";
            }
        }

        private static string ToAbsoluteAssetPath(string unityAssetPath)
        {
            string relative = unityAssetPath.Replace('\\', '/');
            if (relative.StartsWith("Assets/", StringComparison.OrdinalIgnoreCase))
                relative = relative.Substring("Assets/".Length);
            return Path.Combine(Application.dataPath, relative);
        }
    }
}
